<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MassTransit.Worker-7796b5ca-70bf-4b2d-9d53-dfa3af26b61b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.1.0" />
    <PackageReference Include="MassTransit.Azure.ServiceBus.Core" Version="9.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MassTransit.Contract\MassTransit.Contract.csproj" />
  </ItemGroup>
</Project>
