<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MassTransit.RoutingSlip-bd9f8fce-27e4-4a55-b9f8-e17eff4118bd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.1.0" />
    <PackageReference Include="MassTransit.Azure.ServiceBus.Core" Version="9.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MassTransit.Contract\MassTransit.Contract.csproj" />
  </ItemGroup>

</Project>
